#include "tash/core/config_sync.h"
#include "tash/util/config_resolver.h"
#include "tash/util/safe_exec.h"

#include <cstdio>
#include <cstdlib>
#include <ctime>
#include <filesystem>
#include <fstream>
#include <sstream>
#include <sys/stat.h>
#include <sys/types.h>
#include <array>

namespace tash::config_sync {

// ── Gitignore template ───────────────────────────────────────

static const char *GITIGNORE_CONTENT =
    "# Auto-generated by tash sync\n"
    "history.db\n"
    "sessions/\n"
    "trash/\n"
    "cache/\n"
    "*.sock\n"
    "*.log\n";

// ── Helpers ──────────────────────────────────────────────────

static bool directory_exists(const std::string &path) {
    struct stat st;
    return stat(path.c_str(), &st) == 0 && S_ISDIR(st.st_mode);
}

static bool create_directory(const std::string &path) {
    std::error_code ec;
    std::filesystem::create_directories(path, ec);
    if (!ec) return true;
    return directory_exists(path);
}

static bool write_file(const std::string &path, const std::string &content) {
    std::ofstream ofs(path);
    if (!ofs.is_open()) return false;
    ofs << content;
    return ofs.good();
}

static std::string make_timestamp() {
    std::time_t now = std::time(NULL);
    char buf[64];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:%S", std::localtime(&now));
    return std::string(buf);
}

// Ensure a path ends with '/'
static std::string ensure_trailing_slash(const std::string &path) {
    if (path.empty() || path[path.size() - 1] != '/') {
        return path + "/";
    }
    return path;
}

// ── run_git_argv ─────────────────────────────────────────────
//
// Build argv directly from the caller's vector -- no shell -- and run
// via the safe-exec helper. A prior implementation used
// popen("git -C \"" + config_dir + "\" " + git_args), which quoted
// config_dir with plain double quotes and left git_args unquoted; a
// config_dir containing `"` or a remote URL containing `;` / `$(...)`
// was a direct command-injection vector.
//
// Fix (see security review #3): assemble argv = {"git", "-C", dir, ...}
// and hand to safe_exec which forks and calls the raw syscall with no
// shell in between.

CmdResult run_git_argv(const std::string &config_dir,
                       const std::vector<std::string> &git_args) {
    CmdResult result;
    result.exit_code = -1;

    std::vector<std::string> argv;
    argv.reserve(3 + git_args.size());
    argv.push_back("git");
    argv.push_back("-C");
    argv.push_back(config_dir);
    for (const auto &a : git_args) argv.push_back(a);

    auto r = tash::util::safe_exec(argv);
    result.exit_code = r.exit_code;
    result.output = r.stdout_text;
    return result;
}

// ── get_tash_config_dir ──────────────────────────────────────

std::string get_tash_config_dir() {
    std::string config_dir = tash::config::get_data_dir();
    if (config_dir.empty()) return "";
    create_directory(config_dir);
    return ensure_trailing_slash(config_dir);
}

// ── sync_init ────────────────────────────────────────────────

bool sync_init(const std::string &config_dir) {
    if (config_dir.empty()) return false;

    // Ensure directory exists
    if (!create_directory(config_dir)) {
        return false;
    }

    // Initialize git repo (idempotent -- git init on existing repo is fine)
    CmdResult init_result = run_git_argv(config_dir, {"init"});
    if (init_result.exit_code != 0) {
        return false;
    }

    // Create .gitignore (overwrite if exists to ensure correct content)
    std::string gitignore_path = ensure_trailing_slash(config_dir) + ".gitignore";
    if (!write_file(gitignore_path, GITIGNORE_CONTENT)) {
        return false;
    }

    return true;
}

// ── sync_set_remote ──────────────────────────────────────────

bool sync_set_remote(const std::string &config_dir,
                     const std::string &remote_url) {
    if (config_dir.empty() || remote_url.empty()) return false;

    // Try adding origin first. remote_url is now a bare argv token, so a
    // URL containing shell metacharacters can no longer inject.
    CmdResult add_result = run_git_argv(
        config_dir, {"remote", "add", "origin", remote_url});

    if (add_result.exit_code != 0) {
        // Origin already exists -- update the URL
        CmdResult set_result = run_git_argv(
            config_dir, {"remote", "set-url", "origin", remote_url});
        if (set_result.exit_code != 0) {
            return false;
        }
    }

    return true;
}

// ── sync_push ────────────────────────────────────────────────

bool sync_push(const std::string &config_dir) {
    if (config_dir.empty()) return false;

    // Stage all changes
    CmdResult add_result = run_git_argv(config_dir, {"add", "-A"});
    if (add_result.exit_code != 0) {
        return false;
    }

    // Commit with timestamp (commit message is a single argv token now,
    // so whitespace / quotes in the timestamp format are passed through
    // verbatim).
    std::string timestamp = make_timestamp();
    std::string commit_msg = "tash config sync " + timestamp;
    CmdResult commit_result = run_git_argv(
        config_dir, {"commit", "-m", commit_msg});
    // If nothing to commit, exit_code will be 1 -- we treat that as OK
    // but only if there's genuinely nothing to commit
    if (commit_result.exit_code != 0) {
        // Check if "nothing to commit" -- still proceed to push
        if (commit_result.output.find("nothing to commit") == std::string::npos) {
            return false;
        }
    }

    // Push
    CmdResult push_result = run_git_argv(
        config_dir, {"push", "origin", "master"});
    if (push_result.exit_code != 0) {
        return false;
    }

    return true;
}

// ── sync_pull ────────────────────────────────────────────────

bool sync_pull(const std::string &config_dir) {
    if (config_dir.empty()) return false;

    CmdResult pull_result = run_git_argv(
        config_dir, {"pull", "origin", "master"});
    return pull_result.exit_code == 0;
}

// ── sync_diff ────────────────────────────────────────────────

std::string sync_diff(const std::string &config_dir) {
    if (config_dir.empty()) return "";

    std::ostringstream oss;

    // git diff HEAD (shows staged + unstaged diff from last commit)
    CmdResult diff_result = run_git_argv(config_dir, {"diff", "HEAD"});
    if (!diff_result.output.empty()) {
        oss << diff_result.output;
    }

    // git status --short
    CmdResult status_result = run_git_argv(config_dir, {"status", "--short"});
    if (!status_result.output.empty()) {
        if (!oss.str().empty()) {
            oss << "\n";
        }
        oss << status_result.output;
    }

    return oss.str();
}

// ── sync_is_initialized ──────────────────────────────────────

bool sync_is_initialized(const std::string &config_dir) {
    if (config_dir.empty()) return false;

    std::string git_dir = ensure_trailing_slash(config_dir) + ".git";
    return directory_exists(git_dir);
}

} // namespace tash::config_sync
